### ISSUE TITLE
The touchpad is not recognized in the RoboRecall

### ISSUE THREAD

**Issue by Boeforgithub** [NOLOVR/NOLO-Driver-For-Windows#16]
If I play oculus game using revive, the touch pad is not recognized in the game.

 So I can not play RoboRecalll.

 Is there a solution?

**Comment by Boeforgithub** [comment]
Some people have problems like that: "When I start up any Oculus game using Revive, there are a few issues with the controller.  It thinks I am holding down-left on the left thumbstick, the triggers act weird and won't select things, the grip buttons become a toggle instead of hold, and everything is essentially unplayable."

**Comment by mnbvcxzl90** [comment]
Use the RoboRevive mod. It makes it so the game plays better with the Vive but works perfectly fine with Nolo & Riftcat. It's how I play the game as Revive doesn't seem to map things correctly. Also this issue is more with Revive itself and not Nolo as the Nolo controllers function pretty much identical to the Vive controllers. 

https://github.com/LibreVR/RoboRevive

**Comment by Boeforgithub** [comment]
I tried using RoboRevive mod, but telepot don't worked, when I pushed nolo touch pad. Maybe the problem is more with Revive itself and not Nolo...
